# Лабораторна робота №1 
# Воробйов Георгій
# Група КА-91
# Варіант 4

# Умова
Дано масив T, який складається з N рядкiв, якi вiдповiдають прикладам, i m стовпчикiв, якi вiдповiдають ознакам. Вiдомо, що ознака x<sub>h</sub> приймає значення з множини {c<sub>h<sub>1</sub></sub>, c<sub>h<sub>2</sub></sub>, ..., c<sub>h<sub>q<sub>h</sub></sub></sub>}. Дано вектор y розмiрностi N, елементи якого приймають значення з множини S = {s<sub>1</sub>, s<sub>2</sub>, ..., s<sub>v</sub>} (мiтки класiв для прикладiв). Знайти ознаку x<sup>*</sup><sub>h</sub> та значення цiєї ознаки с<sub>hi</sub><sup>∗</sup>:

$$c^*_{hi} = \arg\min_{h, i}Er(h, i)$$

$$Er(h, i) = \frac{p_3(y \neq s_j^* \vert x_h = c_{hi})}{p_1(x_h = c_{hi})}$$

$$s_j^* = \arg\max_j p_2(y=s_j \vert x_h = c_{hi})$$

де $p_1(x_h = c_{hi})$ - кiлькiсть прикладiв, для яких ознака $x_h$ приймає значення $c_{hi}$, $p_2(y = s_j\vert x_h = c_{hi})$ - кiлькiсть прикладiв, якi належать класу $s_j$ i ознака $x_h$ приймає значення $c_{hi}$, $s^∗_j$ - найбiльш iмовiрний клас за умови
що ознака $x_h$ приймає значення $c_{hi}$.

Import important stuff

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display, Math
N = 5
M = 10

Generate random data

In [2]:
X = np.random.randint(1, 10, (N, M))
X

array([[8, 5, 4, 5, 6, 2, 3, 6, 7, 4],
       [6, 1, 5, 4, 1, 9, 6, 1, 3, 6],
       [4, 7, 5, 2, 2, 5, 4, 5, 2, 9],
       [6, 9, 9, 1, 2, 3, 4, 8, 4, 4],
       [4, 5, 3, 4, 1, 3, 2, 6, 8, 8]])

In [3]:
Y = np.random.randint(1, 10, N)
S = np.unique(Y)
Y

array([9, 1, 3, 4, 7])

Get the values for $c_{hi}$ (unique values of a column)

Find $s_j^*$ common values for each value of S(calculate $p_2$)

In [4]:
C = []
for i in range(X.shape[1]):
    C.append(np.unique(X[:, i] ))
C

[array([4, 6, 8]),
 array([1, 5, 7, 9]),
 array([3, 4, 5, 9]),
 array([1, 2, 4, 5]),
 array([1, 2, 6]),
 array([2, 3, 5, 9]),
 array([2, 3, 4, 6]),
 array([1, 5, 6, 8]),
 array([2, 3, 4, 7, 8]),
 array([4, 6, 8, 9])]

find $Er$ for specific $c_{hi}$ using formula
$$Er(h, i) = 1 - \frac{p_3(y = s_j^* \vert x_h = c_{hi})}{p_1(x_h = c_{hi})} = 1- \frac{s_j^*}{p_1(x_h = c_{hi})}$$

In [12]:
def get_error_value_for_specific_characteristic(h, chi):
    correct_lines = X[X[:, h]==chi]
    correct_lines_count = correct_lines.shape[0]
    correct_marks, correct_marks_counts = np.unique(Y[X[:, h]==chi], return_counts=True)
    most_frequent = np.max(correct_marks_counts)
    most_frequent_marks = correct_marks[correct_marks_counts == most_frequent]
    return 1 - most_frequent/correct_lines_count

get minimum for each feature

In [13]:
min_c = np.zeros((2, len(C)))
for i in range(len(C)):
    minimum_error = np.vectorize(lambda x: get_error_value_for_specific_characteristic(i, x))(C[i])
    min_c[0, i] = C[i][np.argmin(minimum_error)]
    min_c[1, i] = np.min(minimum_error)
min_c

array([[8.        , 8.        , 8.        , 8.        , 4.        ,
        8.        , 8.        , 1.        , 7.        , 9.        ],
       [0.55555556, 0.55555556, 0.63636364, 0.55555556, 0.6875    ,
        0.58333333, 0.57142857, 0.66666667, 0.57142857, 0.33333333]])

In [14]:
xh_star = np.argmin(min_c[1])
chi_star = min_c[0][xh_star]
display(Math(f"x_h^* = {xh_star}"))
display(Math(r"c_{hi}^* = " + f"{chi_star}"))

<IPython.core.display.Math object>

<IPython.core.display.Math object>